### PR TITLE
Change sanity_check in yield-generator-oscillator.py to accept long integers for maxoffer and minoffer.

### PR DESCRIPTION
**Pull request by jamesphillipturpin**
Python 2.7 does not necessarily support 64 bit integers for type int. It's not uncommon that Python 2.7 for Windows will only allow 32 bit signed integers for type int, and that larger integers will be supported as type long. As a result values as low as pow(2,31) = 214783648 santoshis = 21.47483648 bitcoin will be stored as a long in that case, even if one attempts to cast them as int. Changing the sanity test to allow type long seems to be the minimum change to fix this problem without creating conflicts for other users.

Previously I submitted a similar pull request (#545), to joinmarket:master rather than joinmarket:develop, which I will be closing presently.

### CODE REVIEW

**Comment by chris-belcher** [comment]
you have to merge it into joinmarket-org/joinmarket not jamesphillipturpin/joinmarket :)

**Comment by raedah** [comment]
Can you fix the comment on the git commit?

**Comment by jamesphillipturpin** [comment]
Apparently not. I already tried. The github website is rather non-intuitive
in its user interface. I've described the problem and made two pull
requests. I'm probably going to delete my account and go on my way,
disappear into the night.

**Comment by chris-belcher** [comment]
Everyone is a bit derpy when they first start, dont worry about it :)
Come on IRC

**Pull request closed without merging**
